server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 20
        limit-refresh-period: 10S
  retry:
    instances:
      default:
        max-attempts: 3      
spring:
  application:
    name: conta-corrente
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projeto?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/projeto?useTimezone=true&serverTimezone=UTC
    user: root
    password: admin123
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
springdoc:
  show-actuator: true
  api-docs:
    path: conta-corrente/v3/api-docs
